services:
  - type: web
    name: portfolio-backend
    env: python
    repo: https://github.com/irshad12332123/portfolio.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
